import { ExecutionContext } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';
import { FindOperator } from 'typeorm';
import { FieldMapper } from '@nestjs-yalc/interfaces/maps.interface';
import { AgQueryParams } from './ag-grid.args';
import { FilterType } from './ag-grid.enum';
import { AgGridFindManyOptions, DateFilterModel, FilterInput, FilterModel, CombinedWhereModel, CombinedSimpleModel, SimpleFilterModel, SetFilterModel, AgGridArgsOptions, AgGridArgsSingleOptions } from './ag-grid.interface';
import { WhereCondition, WhereConditionType } from './ag-grid.type';
import { GraphQLResolveInfo } from 'graphql';
import { FilterOption } from './object.decorator';
export declare function getTextFilter(filter: string, firstParameter: string): FindOperator<string>;
export declare function getNumberFilter(filter: string, firstParameter: number, secondParameter?: number): FindOperator<number>;
export declare function getDateFilter(filter: string, firstParameter: string, secondParameter?: string): FindOperator<string>;
export declare function filterSwitch(filter: FilterModel, filterName?: string): FindOperator<number | string | Date | null>;
export declare function getFindOperator(filterType: FilterType, filterName: string, arg1: any, arg2?: any): FindOperator<number | string | Date | null>;
export declare function convertFilter(filter: FilterModel | CombinedSimpleModel): FindOperator<string | number | Date | null> | CombinedWhereModel;
export declare function resolveFilter(filter: CombinedSimpleModel | SimpleFilterModel | DateFilterModel | SetFilterModel): WhereConditionType;
export declare function createWhere(filtersObject: FilterInput, fieldMapper: FieldMapper | undefined, alias?: string, where?: WhereCondition): WhereCondition;
export declare function removeSymbolicSelection(select: string[], data: FieldMapper | undefined, path: string): string[];
export declare function checkFilterScope(where: WhereCondition, filterOption: FilterOption): void;
export declare function mapAgGridParams(params: AgGridArgsOptions | undefined, ctx: GqlExecutionContext, args: AgQueryParams, info: GraphQLResolveInfo): AgGridFindManyOptions;
export declare const AgGridArgsFactory: <T>(data: AgGridArgsOptions | undefined, ctx: ExecutionContext) => AgGridFindManyOptions<T>;
export declare const AgGridArgsMapper: <T>(...dataOrPipes: (import("@nestjs/common").PipeTransform<any, any> | import("@nestjs/common").Type<import("@nestjs/common").PipeTransform<any, any>> | AgGridArgsOptions | undefined)[]) => ParameterDecorator;
export declare const AgGridCombineDecorators: (params: AgGridArgsOptions) => (target: any, key: string, index: number) => void;
export declare const AgGridArgs: (params: AgGridArgsOptions) => (target: any, key: string, index: number) => void;
export declare const AgGridArgsNoPagination: (params: AgGridArgsOptions) => (target: any, key: string, index: number) => void;
export declare function AgGridArgsSingleDecoratorMapper<T>(params: AgGridArgsOptions | undefined, args: AgQueryParams, info: GraphQLResolveInfo): AgGridFindManyOptions<T>;
export declare const AgGridArgsSingleDecoratorFactory: <T>(data: AgGridArgsOptions | undefined, ctx: ExecutionContext) => AgGridFindManyOptions<T>;
export declare const AgGridArgsSingleDecorator: <T>(...dataOrPipes: (import("@nestjs/common").PipeTransform<any, any> | import("@nestjs/common").Type<import("@nestjs/common").PipeTransform<any, any>> | AgGridArgsOptions | undefined)[]) => ParameterDecorator;
export declare const AgGridArgsSingle: (params: AgGridArgsSingleOptions) => (target: any, key: string, index: number) => void;
